// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWarsTimelines.Persistence;

#nullable disable

namespace StarWarsTimelines.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260822004440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlanetBornOnId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SpeciesId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearOfBirthEarliest")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearOfBirthLatest")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearOfDeathEarliest")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearOfDeathLatest")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PlanetBornOnId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.EventCharacter", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("EventCharacters", (string)null);
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.EventLocation", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("EventLocations", (string)null);
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.EventVehicle", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId", "VehicleId");

                    b.HasIndex("VehicleId");

                    b.ToTable("EventVehicles", (string)null);
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.SourceMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SourceMaterials", (string)null);
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.SourceMaterialEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayDateEnd")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceMaterialId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceMaterialUnitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceMaterialId");

                    b.HasIndex("SourceMaterialUnitId");

                    b.ToTable("SourceMaterialEvents", (string)null);
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.SourceMaterialUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SourceMaterialId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceMaterialId", "GroupNumber", "Number")
                        .IsUnique();

                    b.ToTable("SourceMaterialUnits", (string)null);
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.Species", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HomePlanetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HomePlanetId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Species", (string)null);
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailVerificationTokenExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailVerificationTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailVerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.UserSourceMaterial", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceMaterialId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "SourceMaterialId");

                    b.HasIndex("SourceMaterialId");

                    b.ToTable("UserSourceMaterials", (string)null);
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.UserSourceMaterialUnit", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceMaterialUnitId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "SourceMaterialUnitId");

                    b.HasIndex("SourceMaterialUnitId");

                    b.ToTable("UserSourceMaterialUnits", (string)null);
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.Character", b =>
                {
                    b.HasOne("StarWarsTimelines.Domain.Entities.Location", "PlanetBornOn")
                        .WithMany()
                        .HasForeignKey("PlanetBornOnId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StarWarsTimelines.Domain.Entities.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlanetBornOn");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.EventCharacter", b =>
                {
                    b.HasOne("StarWarsTimelines.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsTimelines.Domain.Entities.SourceMaterialEvent", "SourceMaterialEvent")
                        .WithMany("EventCharacters")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("SourceMaterialEvent");
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.EventLocation", b =>
                {
                    b.HasOne("StarWarsTimelines.Domain.Entities.SourceMaterialEvent", "SourceMaterialEvent")
                        .WithMany("EventLocations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsTimelines.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("SourceMaterialEvent");
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.EventVehicle", b =>
                {
                    b.HasOne("StarWarsTimelines.Domain.Entities.SourceMaterialEvent", "SourceMaterialEvent")
                        .WithMany("EventVehicles")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsTimelines.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceMaterialEvent");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.SourceMaterialEvent", b =>
                {
                    b.HasOne("StarWarsTimelines.Domain.Entities.SourceMaterial", "SourceMaterial")
                        .WithMany()
                        .HasForeignKey("SourceMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsTimelines.Domain.Entities.SourceMaterialUnit", "SourceMaterialUnit")
                        .WithMany()
                        .HasForeignKey("SourceMaterialUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceMaterial");

                    b.Navigation("SourceMaterialUnit");
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.SourceMaterialUnit", b =>
                {
                    b.HasOne("StarWarsTimelines.Domain.Entities.SourceMaterial", "SourceMaterial")
                        .WithMany("SourceMaterialUnits")
                        .HasForeignKey("SourceMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceMaterial");
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.Species", b =>
                {
                    b.HasOne("StarWarsTimelines.Domain.Entities.Location", "HomePlanet")
                        .WithMany()
                        .HasForeignKey("HomePlanetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HomePlanet");
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.UserSourceMaterial", b =>
                {
                    b.HasOne("StarWarsTimelines.Domain.Entities.SourceMaterial", "SourceMaterial")
                        .WithMany()
                        .HasForeignKey("SourceMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsTimelines.Domain.Entities.User", "User")
                        .WithMany("UserSourceMaterials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceMaterial");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.UserSourceMaterialUnit", b =>
                {
                    b.HasOne("StarWarsTimelines.Domain.Entities.SourceMaterialUnit", "SourceMaterialUnit")
                        .WithMany()
                        .HasForeignKey("SourceMaterialUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsTimelines.Domain.Entities.User", "User")
                        .WithMany("UserSourceMaterialUnits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceMaterialUnit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.SourceMaterial", b =>
                {
                    b.Navigation("SourceMaterialUnits");
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.SourceMaterialEvent", b =>
                {
                    b.Navigation("EventCharacters");

                    b.Navigation("EventLocations");

                    b.Navigation("EventVehicles");
                });

            modelBuilder.Entity("StarWarsTimelines.Domain.Entities.User", b =>
                {
                    b.Navigation("UserSourceMaterialUnits");

                    b.Navigation("UserSourceMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
